import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import PageHeader from '@/components/page-header';
import PageFooter from '@/components/page-footer';
import { ApolloWrapper } from '@/components/apollo-wrapper';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen bg-background font-sans`}
      >
        <ApolloWrapper>
          <PageHeader />
          <div className="container max-w-screen-2xl">{children}</div>
          <PageFooter />
        </ApolloWrapper>
      </body>
    </html>
  );
}
